<a href="https://colab.research.google.com/github/chuancao26/islp/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Data Manipulation

## 1 . Run the code in this section. Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [ ]:
X==Y, (X < Y), (X > Y)

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

## 2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [ ]:
a = torch.zeros(1,3,3)

In [ ]:
b = torch.ones(1,3
               )
a + b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

# Data Preprocessing

## 1. Try loading datasets, e.g., Abalone from the UCI Machine Learning Repository and inspect their properties. What fraction of them has missing values? What fraction of the variables is numerical, categorical, or text?

In [ ]:
!pip install ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo
import pandas as pd
# fetch dataset
student_performance = fetch_ucirepo(id=320)
X = student_performance.data.features
y = student_performance.data.targets

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64 
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64 
 7   Fedu        649 non-null    int64 
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64 
 13  studytime   649 non-null    int64 
 14  failures    649 non-null    int64 
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher    

In [ ]:
y

,G1,G2,G3
0,0,11,11
1,9,11,11
2,12,13,12
3,14,14,14
4,11,13,13
...,...,...,...
644,10,11,10
645,15,15,16
646,11,12,9
647,10,10,10


In [ ]:
X.isna().sum()

,0
school,0
sex,0
age,0
address,0
famsize,0
Pstatus,0
Medu,0
Fedu,0
Mjob,0
Fjob,0


In [ ]:
numeric = X.select_dtypes(include=["number"])
print(f"Porcentaje de variables numericas: {numeric.shape[1]/X.shape[1]: .2f}")
categorical = X.select_dtypes(include=["object", "category"])
print(f"Porcentaje de variables categoricas: {categorical.shape[1]/X.shape[1]: .2f}")

Porcentaje de variables numericas:  0.43
Porcentaje de variables categoricas:  0.57


In [8]:
a = torch.arange(4).reshape(2,2)
a = a.sum(1, keepdim=True)

In [9]:
b = torch.arange(6).reshape(2,3)
b / a

tensor([[0.0000, 1.0000, 2.0000],
        [0.6000, 0.8000, 1.0000]])

## linear algebra


In [3]:

a = torch.arange(12).reshape(3,4)
a == (a.T).T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [5]:
b = torch.linspace(1, 34, 12).reshape(3, 4)
(a + b).T == a.T + b.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

In [7]:
b = torch.linspace(1, 100, 24).reshape(2,3, 4)
len(b)

2

In [8]:
a = torch.ones(4).reshape(2,2)
a / a.sum(axis=1)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [10]:
a = torch.linspace(2,30,24).reshape(2,3,4)
for i in [0, 1, 2]:
  print(f"sum in axis {i}: {a.sum(axis=i)} con un shape de {a.sum(axis=i).shape}")

sum in axis 0: tensor([[18.6087, 21.0435, 23.4783, 25.9130],
        [28.3478, 30.7826, 33.2174, 35.6522],
        [38.0870, 40.5217, 42.9565, 45.3913]]) con un shape de torch.Size([3, 4])
sum in axis 1: tensor([[20.6087, 24.2609, 27.9130, 31.5652],
        [64.4348, 68.0870, 71.7391, 75.3913]]) con un shape de torch.Size([2, 4])
sum in axis 2: tensor([[ 15.3043,  34.7826,  54.2609],
        [ 73.7391,  93.2174, 112.6956]]) con un shape de torch.Size([2, 3])


In [12]:
torch.linalg.norm(a)

tensor(88.5909)

In [18]:
a = torch.arange(100*200).reshape(100, 200)
b = torch.arange(100*200).reshape(100, 200)
c = torch.arange(100*200).reshape(100, 200)
torch.tensor([a, b, c]).shape

TypeError: only integer tensors of a single element can be converted to an index